#!/bin/bash
IP_DIR=/etc/sysconfig/network-scripts
IPFILE=ifcfg-ens33

if [ ! -f $IP_DIR/$IPFILE_`date +%F`.bak]; then
  cp $IP_DIR/$IP_FILE $IP_DIR/$IPFILE_`date +%F`.bak
fi

read -p "Enter ip addr: " IPADDR
grep -hi 'dhcp' $IP_DIR/$IP_FILE >> /dev/null 2>&1
if [ $? -eq 0 ]; then
  sed -i "s/dhcp/static/g" $IP_DIR/$IPFILE
  echo "IPADDR=$IPADDR" >> $IP_DIR/$IPFILE
  echo "NETMASK=255.255.255.0" >> $IP_DIR/$IPFILE
  echo "GATEWAY=192.168.31.2" >> $IP_DIR/$IPFILE
  echo "DNS1=202.96.134.133" >> $IP_DIR/$IPFILE
else
  grep $IPADDR $IP_DIR/$IPFILE >> /dev/null 2>&1
  if [ $? -eq 0 ]; then
    echo "nothing to do"
    exit 1
  else
    sed -i "s/`grep IPADDR $IP_DIR/$IPFILE|sed 's/IPADDR=//g'`/$IPADDR/g" $IP_DIR/$IPFILE
  fi                  
fi
