#!/bin/bash
IP_DIR=/etc/sysconfig/network-scripts/
IPADDR=192.168.31.133
cp $IP_DIRifcfg-ens33 $IP_DIRifcfg-ens33.bak
grep -hi 'dhcp' $IP_DIRifcfg-ens33
if [ $?=0 ];then
  cat > $IP_DIRifcfg-ens33 <<- EOF
    TYPE=Ethernet
    BOOTPROTO=static
    DEFROUTE=yes
    PEERDNS=yes
    PEERROUTES=yes
    IPV4_FAILURE_FATAL=no
    IPV6INIT=yes
    IPV6_AUTOCONF=yes
    IPV6_DEFROUTE=yes
    IPV6_PEERDNS=yes
    IPV6_PEERROUTES=yes
    IPV6_FAILURE_FATAL=no
    IPV6_ADDR_GEN_MODE=stable-privacy
    NAME=ens33
    UUID=c5a0683e-bd47-4dd3-a3ca-063b944372ec
    DEVICE=ens33
    ONBOOT=yes
    IPADDR=$IPADDR
    NETMASK=255.255.255.0
    GATEWAY=192.168.31.2
    DNS1=202.96.134.133
  EOF
else
  echo "nothing to do !"
  exit 1
fi
